### ISSUE TITLE
Endpoint requests not working using firefox

### ISSUE THREAD

**Issue by JB02S** [03y/boozer#7]
Navigating to one of the backend endpoints using firefox results in

![image](https://github.com/user-attachments/assets/eb14c448-aa71-4140-8980-0f94ee3c6df1)

**Comment by 03y** [comment]
This is a firefox thing, choosing a different port should fix. See [here](https://old.reddit.com/r/firefox/comments/ttms50/since_when_was_this_a_thing_in_firefox_trying_to/).

For allowing access to the port see [here](https://support.mozilla.org/en-US/questions/1083282).
